""" Auto-generated by openapi-client-generator
https://github.com/avanov/openapi-client-generator
"""
from enum import Enum
from typing import NamedTuple, Callable, Optional, Type, Mapping, Union

from petstore_full.common import http
from petstore_full.common.types import *


__all__ = (
    "call",
    "Query",
    "Response",
)


class Query(NamedTuple):
    """Parameters for the endpoint query string"""

    status: Optional[status] = None


Response = Sequence[Pet]


class Headers(NamedTuple):
    """"""

    accept_charset: str = "utf-8"

    accept: str = "application/json"

    authorization: Optional[str] = None


METHOD = http.Method(__name__.split(".")[-1])
URL = "pet/findByStatus"


parse_query, dump_query = dasherized & {} ^ Query


parse_headers, dump_headers = dasherized ^ Headers


parse_response, dump_response = camelized & {} ^ Response


def call(
    client: http.Client,
    query: Query,
    headers: Headers,
) -> Response:

    url = URL

    resp = client.make_call(
        method=METHOD,
        url=url,
        headers=dump_headers(headers),
        query=dump_query(query),
        is_stream=False,
    )
    return parse_response(resp.json())
