""" Auto-generated by openapi-client-generator
https://github.com/avanov/openapi-client-generator
"""
from enum import Enum
from typing import NamedTuple, Callable, Optional, Type, Mapping, Union

from petstore_full.common import http
from petstore_full.common.types import *


__all__ = (
    "call",
    "Params",
    "Query",
    "Request",
    "Response",
)


class Params(NamedTuple):
    """Parameters for the endpoint path placeholders"""

    petId: int


class Query(NamedTuple):
    """Parameters for the endpoint query string"""

    additional_metadata: Optional[str] = None


Request = str

Response = ApiResponse


class Headers(NamedTuple):
    """"""

    accept_charset: str = "utf-8"

    accept: str = "application/json"

    authorization: Optional[str] = None


METHOD = http.Method(__name__.split(".")[-1])
URL = "pet/{pet_id}/uploadImage"


parse_params, dump_params = underscored ^ Params


parse_query, dump_query = dasherized & {} ^ Query


parse_headers, dump_headers = dasherized ^ Headers


parse_request, dump_request = camelized & {} ^ Request


parse_response, dump_response = camelized & {} ^ Response


def call(
    client: http.Client,
    request: Request,
    params: Params,
    query: Query,
    headers: Headers,
) -> Response:

    url = URL.format(**dump_params(params))

    resp = client.make_call(
        method=METHOD,
        url=url,
        headers=dump_headers(headers),
        query=dump_query(query),
        payload=dump_request(request),
        is_stream=False,
    )
    return parse_response(resp.json())
