""" Auto-generated by openapi-client-generator
https://github.com/avanov/openapi-client-generator
"""
from typing import NamedTuple, Callable, Optional

from example_client.common import http, types


__all__ = (
    'call',
    'Params','Query',)


class Params(NamedTuple):
    """ Parameters for the endpoint path placeholders
    """
    petId: int

class Query(NamedTuple):
    """ Parameters for the endpoint query string
    """
    additionalMetadata: Optional[str] = None





class Headers(NamedTuple):
    """ 
    """
    accept: str = 'application/json'
    
    accept_charset: str = 'utf-8'

METHOD = http.Method(__name__.split('.')[-1])
URL = "pet/{pet_id}/uploadImage"





def call(
    client: http.Client,
    
    params: Params,
    query: Query,
    headers: Headers = Headers(),
) -> None:
    url = '/'.join([client.service_url.rstrip('/'), URL.lstrip('/')])
    response = client.make_call(
        method=METHOD, url=url,
        headers=headers._asdict()
    )
    return None