""" Auto-generated by openapi-client-generator
https://github.com/avanov/openapi-client-generator
"""
from enum import Enum
from typing import NamedTuple, Callable, Optional

from example_client.common import http
from example_client.common.types import *


__all__ = (
    "call",
    "Params",
    "Query",
    "Request",
    "Response",
)


class Params(NamedTuple):
    """Parameters for the endpoint path placeholders"""

    petId: int


class Query(NamedTuple):
    """Parameters for the endpoint query string"""

    additional_metadata: Optional[str] = None


Request = str

Response = ApiResponse


class Headers(NamedTuple):
    """"""

    accept: str = "application/json"

    accept_charset: str = "utf-8"

    authorization: Optional[str] = None


METHOD = http.Method(__name__.split(".")[-1])
URL = "pet/{pet_id}/uploadImage"


parse_query, dump_query = dasherized(Query)


parse_request, dump_request = camelized(Request)


parse_response, serialize_response = camelized(Response)


def call(
    client: http.Client,
    request: Request,
    params: Params,
    query: Query,
    headers: Headers = Headers(),
) -> Response:

    url = URL.format(**params._asdict())

    resp = client.make_call(
        method=METHOD,
        url=url,
        headers=headers._asdict(),
        query=dump_query(query),
        payload=dump_request(request),
        is_stream=False,
    )
    return parse_response(resp.json())
