""" Auto-generated by openapi-client-generator
https://github.com/avanov/openapi-client-generator
"""
from enum import Enum
from typing import NamedTuple, Callable, Optional, Type, Mapping, Union

from callback_example.common import http
from callback_example.common.types import *


__all__ = (
    "call",
    "Query",
    "Response",
)


class Query(NamedTuple):
    """Parameters for the endpoint query string"""

    callback_url: str


class Response(NamedTuple):
    """"""

    subscription_id: str


class Headers(NamedTuple):
    """"""

    accept_charset: str = "utf-8"

    accept: str = "application/json"

    authorization: Optional[str] = None


METHOD = http.Method(__name__.split(".")[-1])
URL = "streams"


query_overrides: Mapping[str, Any] = {}
parse_query, dump_query = dasherized & query_overrides ^ Query


parse_headers, dump_headers = dasherized ^ Headers


response_overrides: Mapping[str, Any] = {}
parse_response, dump_response = camelized & response_overrides ^ Response


IS_STREAMING_RESPONSE = False


def call(
    client: http.Client,
    query: Query,
    headers: Headers,
) -> Response:

    url = URL

    resp = client.make_call(
        method=METHOD,
        url=url,
        headers=dump_headers(headers),
        query=dump_query(query),
        is_stream=IS_STREAMING_RESPONSE,
    )
    return parse_response(resp.json())
