""" Auto-generated by openapi-client-generator
https://github.com/avanov/openapi-client-generator
"""
from typing import NamedTuple, Callable, Optional

from example_client.common import http
from example_client.common.types import *


__all__ = (
    "call",
    "Request",
)


Request = User


class Headers(NamedTuple):
    """"""

    accept: str = "application/json"

    accept_charset: str = "utf-8"

    authorization: Optional[str] = None


METHOD = http.Method(__name__.split(".")[-1])
URL = "user"


parse_request, serialize_request = generate_constructor_and_serializer(Request)


def call(
    client: http.Client,
    request: Request,
    headers: Headers = Headers(),
) -> None:

    url = URL

    response = client.make_call(
        method=METHOD,
        url=url,
        headers=headers._asdict(),
        payload=request._asdict(),
    )
    return None
